apiVersion: v1
kind: Pod
metadata:
  name: nginx-emptydir
  labels:
    name: nginx-emptydir
spec:
  volumes:
    - name: html
      emptyDir: {}
  containers:
  - name: nginx
    image: nginx:alpine
    volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: html
        readOnly: true
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  - name: html-uploader
    image: alpine
    command: ["/bin/sh" , "-c"]
    args: 
      - while true; do date >> /html/index.html; anwar >> /html/index.html; sleep 10; done
    volumeMounts:
      - mountPath: /html
        name: html
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
